name: Check codestyle

on:
  push:
    branches: [ci_codestyle_runner]
  pull_request:
    branches: [ci_codestyle_runner]

env:
  SSL_CERT_DIR: /etc/ssl/certs
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
  DOCKER_TLS_VERIFY: 0
  SSL_NO_VERIFY: 0
  PYTHONHTTPSVERIFY: 0
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  build:
    runs-on: [self-hosted, Linux]
    strategy:
      # For debbug purposes
      fail-fast: false
      matrix:
        python-version: ["3.10.3"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install -- upgrade pip
        pip install mypy pylint flake8 pytest
    # - name: "Check type hints by mypy"
      # run: |
      #   mypy --ignore-missing-imports .gitignore
      #   flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    # - name: Analysing the code with pylint
    #   run: |
    #     pylint $(git ls-files '*.py')

# steps:
# - uses: actions/checkout@v3
# - name: Install poetry
#   run: pipx install poetry
# - uses: actions/setup-python@v3
#   with:
#     python-version: '3.9'
#     cache: 'poetry'
# - run: poetry install
# - run: poetry run pytest
