name: Check codestyle

on:
  push:
    branches: [ci_codestyle_runner]
  pull_request:
    branches: [ci_codestyle_runner]

envs:
#  SSL_CERT_DIR: /etc/ssl/certs
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  build:
    runs-on: [self-hosted, Windows]
    strategy:
      # For debbug purposes
      fail-fast: false
      matrix:
        python-version: ["3.10.3", "3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -- upgrade pip
